sudo: true
dist: trusty
language: node_js
node_js:
  - "8"
cache: yarn
before_install:
  - yarn
stages:
  - test
  - name: build
    if: branch = master
  - name: deploy
    if: branch = master  
jobs:
  include:
    - stage: test
      script: yarn test
    - stage: build
      before_script:
      - git diff --name-only $TRAVIS_COMMIT_RANGE > gitchanges.txt 
      - node ./scripts/getChanges.js
      script: 
      - cat ./gitchanges.txt
      - cat ./scripts/toBuild.json
      - node ./scripts/build.js
    - stage: deploy
      script: 
      - echo "Deploy to Kubernetes"
      - echo $TRAVIS_BUILD_NUMBER 