language: node_js
node_js:
  - "stable"
before_install:
  - npm i -g npm@latest
install:
  - npm install
cache:
  directories:
    - "node_modules"
before_script: 
  - cd services
  - cd iam
  - cd test
script: 
  - node_js integration.spec.js
