sudo: true
dist: trusty
language: node_js
node_js:
  - "8"
before_install:
  - yarn
  
jobs:
  include:
    - stage: Test
      script: yarn test
    - stage: Build-Upload
      before_script:
      - git diff --name-only $TRAVIS_COMMIT_RANGE > gitchanges.txt 
      - node ./scripts/getChanges.js
      script: 
      - cat ./gitchanges.txt
      - cat ./scripts/toBuild.json
      - node ./scripts/build.js
    - stage: Deploy
      script: 
      - echo "Deploy to Kubernetes"
      - echo $TRAVIS_BUILD_NUMBER 
branches:
  only:
  - master