apiVersion: v1
kind: Service
metadata:
  labels:
    app: oih-iam
  name: oih-iam
  namespace: oih-dev-ns
spec:
  type: NodePort
  selector:
      app: oih-iam
  ports:
    - port: 3099
      targetPort: 3099
      protocol: TCP
