version: 2.1

aliases:
  - &nodeenv
    - image: circleci/node:8-stretch
  - &run_npm_install
    name: Installing Dependencies
    command: yarn
jobs:
  dep:
    docker: *nodeenv
    working_directory: ~/oih
    steps: 
      - checkout: 
          path: ~/oih
      - run: *run_npm_install
      - save_cache: 
          key: yarn-deps
          paths:
            - ~/oih
  iam-test:
    docker: *nodeenv
    working_directory: ~/oih/services/iam
    steps: 
      - restore_cache:
          keys:
            - yarn-deps
      - run: yarn test

workflows:
  pipeline_iam:
    jobs:
      - dep
      - iam-test:
          requires:
            - dep
        