version: 2.1

aliases:
  - &nodeenv
    - image: circleci/node:8-stretch
  - &restore_cache_dependencies
    name: Restoring from the cache
    key: v1-node-modules-cache-{{ checksum "package.json" }}
  - &run_npm_install
    name: Installing Dependencies
    command: yarn
  - &save_cache_dependencies
    name: Saving into the cache
    key: v1-node-modules-cache-{{ checksum "package.json" }}
    paths:
      - ~/.cache/yarn
jobs:
  dep:
    docker: *nodeenv
    working_directory: ~/oih
    steps: 
      - checkout: 
          path: ~/oih
      - run: *run_npm_install
      - save_cache: 
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/oih
  iam-test:
    docker: *nodeenv
    working_directory: ~/oih/services/iam
    steps: 
      - checkout: 
          path: ~/oih
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: yarn test

workflows:
  pipeline_iam:
    jobs:
      - dep
      - iam-test:
          requires:
            - iam
        