version: 2.1

aliases:
  - &node_env
    - image: circleci/node:8-stretch
  - &node_mongo_env
    - image: circleci/node:8-stretch
    - image: circleci/mongo:3.6
  - &run_npm_install
    name: Installing Dependencies
    command: yarn
  - &set_version
    run: |
      export VERSION=`node -e "const fs = require('fs'); console.log(JSON.parse(fs.readFileSync('./package.json')).version);"`
      echo $VERSION-$CIRCLE_BUILD_NUM > version
  - &set_servicename
    run: basename $PWD > servicename
  - &only_master_filter
    branches:
      only: master
  - &basaas_test_steps
      - restore_cache:
          keys:
            - yarn-deps-{{ .Branch }}-{{ .Revision }}
      - run: yarn test
  - &basaas_build_steps
      - setup_remote_docker
      - restore_cache:
          keys:
            - yarn-deps-{{ .Branch }}-{{ .Revision }}
      - *set_version
      - *set_servicename
      - save_cache: 
          key: yarn-deps-{{ .Branch }}-{{ .Revision }}-build
          paths:
            - ~/oih
      - run: |
          yarn build
          export SERVICENAME=`cat servicename`
          export VERSION=`cat version`
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          yarn run build:docker
          docker tag openintegrationhub/${SERVICENAME}:${VERSION} openintegrationhub/${SERVICENAME}:latest
          docker push openintegrationhub/${SERVICENAME}:${VERSION}
          docker push openintegrationhub/${SERVICENAME}:latest
  - &basaas_deploy_steps
      - restore_cache:
          keys:
            - yarn-deps-{{ .Branch }}-{{ .Revision }}-build
      - run: |
          export SERVICENAME=`cat servicename`
          export VERSION=`cat version`
          # ./scripts/install-gcloud.sh
          echo 'Command  kubectl set image deployment/${servicename}  ${servicename}=openintegrationhub/${servicename}:${VERSION}'
jobs:
  deps:
    docker: *node_env
    working_directory: ~/oih
    steps: 
      - checkout: 
          path: ~/oih
      - run: *run_npm_install
      - save_cache: 
          key: yarn-deps-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/oih
  iam-test:
    docker: *node_env
    working_directory: ~/oih/services/iam
    steps: *basaas_test_steps
  iam-build:
    docker: *node_env
    working_directory: ~/oih/services/iam
    steps: *basaas_build_steps
  iam-deploy:
    docker: *node_env
    working_directory: ~/oih/services/iam
    steps: *basaas_deploy_steps
  secret-service-test:
    docker: *node_env
    working_directory: ~/oih/services/secret-service
    steps: *basaas_test_steps
  secret-service-build:
    docker: *node_env
    working_directory: ~/oih/services/secret-service
    steps: *basaas_build_steps
  secret-service-deploy:
    docker: *node_env
    working_directory: ~/oih/services/secret-service
    steps: *basaas_deploy_steps
workflows:
  pipeline_iam:
    jobs:
      - deps
      - iam-test:
          requires:
            - deps
      - iam-build:
          requires:
            - iam-test
          filters: *only_master_filter
      - iam-deploy:
          requires:
            - iam-build
          filters: *only_master_filter
  pipeline_secret-service:
    jobs:
      - deps
      - secret-service-test:
          requires:
            - deps
      - secret-service-build:
          requires:
            - secret-service-test
          filters: *only_master_filter
      - secret-service-deploy:
          requires:
            - secret-service-build
          filters: *only_master_filter