version: 2

aliases:
  - &docker_environment
    - image: circleci/node:8-stretch
    - image: circleci/mongo:3.6
  - &checkout
    path: ~/oih
  - &restore_cache_dependencies
    name: "Restoring node_modules from the cache"
    keys:
      - node-modules-cache-{{ checksum "~/oih/yarn.lock" }}
  - &run_npm_install
    name: Installing Dependencies
    command: yarn install
  - &save_cache_dependencies
    name: "Saving node_modules into the cache"
    key: node-modules-cache-{{ checksum "~/oih/yarn.lock" }}
    paths:
      - node_modules
  - &run_build
    name: Building an Image
    command: yarn test
  - &common_steps
    - checkout: *checkout
    - restore_cache: *restore_cache_dependencies
    - run: pwd
    - run: ls -la ~/oih/node_modules
    - run: *run_npm_install
    - run: ls -la ~/oih/node_modules
    - save_cache: *save_cache_dependencies
    #- setup_remote_docker
    - run: *run_build
  - &common_environment
    docker: *docker_environment
    steps: *common_steps

jobs:
  communication-router:
    <<: *common_environment
    working_directory: ~/oih/services/communication-router
  flows-operator:
    <<: *common_environment
    working_directory: ~/oih/services/flows-operator
  iam:
    <<: *common_environment
    working_directory: ~/oih/services/iam
  integration-content-repository:
    <<: *common_environment
    working_directory: ~/oih/services/integration-content-repository
  scheduler:
    <<: *common_environment
    working_directory: ~/oih/services/scheduler
  secret-service:
    <<: *common_environment
    working_directory: ~/oih/services/secret-service

workflows:
  version: 2
  build_development:
    jobs:
      - communication-router
      - flows-operator
      - iam
      - integration-content-repository
      - scheduler
      - secret-service
