version: 2

aliases:
  - &nodeenv
    - image: circleci/node:8-stretch
  - &restore_cache_dependencies
    name: Restoring from the cache
    key: v1-node-modules-cache-{{ checksum "package.json" }}
  - &run_npm_install
    name: Installing Dependencies
    command: yarn install
  - &save_cache_dependencies
    name: Saving into the cache
    key: v1-node-modules-cache-{{ checksum "package.json" }}
    paths:
      - ~/.cache/yarn
jobs:
  iam:
    docker: *nodeenv
    working_directory: ~/oih/services/iam
    steps: 
      - checkout: 
          path: ~/oih
      - restore_cache: *restore_cache_dependencies
      - run: *run_npm_install
      - save_cache: *save_cache_dependencies
  test:
    docker: *nodeenv
    steps:
      - run: yarn test
workflows:
  version: 2
  pipeline_iam:
    jobs:
      - iam
      - test:
          requires:
            - iam
        