version: 2.1

aliases:
  - &node_env
    - image: circleci/node:8-stretch
  - &node_mongo_env
    - image: circleci/node:8-stretch
    - image: circleci/mongo:3.6
  - &run_npm_install
    name: Installing Dependencies
    command: yarn

  - &only_master_filter
    branches:
      only: master
  - &basaas_test_steps
      - restore_cache:
          keys:
            - yarn-deps-{{ .Branch }}-{{ .Revision }}
      - run: yarn test
  - &build_steps
      - setup_remote_docker
      - restore_cache:
          keys:
            - yarn-deps-{{ .Branch }}-{{ .Revision }}
      - save_cache: 
          key: yarn-deps-{{ .Branch }}-{{ .Revision }}-build
          paths:
            - ~/oih
      - run: |
          git diff --no-commit-id --name-only -r `git log -n 3 --oneline --pretty=format:"%h" | tail -n1` > gitchanges.txt
          cd ./scripts # needed for compatible with travis implementation
          node getChanges.js
          node build.js
  - &deploy_steps
      - restore_cache:
          keys:
            - yarn-deps-{{ .Branch }}-{{ .Revision }}-build
      - run: |
          git diff --no-commit-id --name-only -r `git log -n 3 --oneline --pretty=format:"%h" | tail -n1` > gitchanges.txt
          cd ./scripts  # needed for compatible with travis implementation
          node getChanges.js
          echo 'Deploy disabled'
          # node deploy.js   # not yet useable because of missing service account
jobs:
  deps:
    docker: *node_env
    working_directory: ~/oih
    steps: 
      - checkout: 
          path: ~/oih
      - run: *run_npm_install
      - save_cache: 
          key: yarn-deps-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/oih
  test:
    docker: *node_env
    steps: 
      - run: echo OK
  iam-test:
    docker: *node_env
    working_directory: ~/oih/services/iam
    steps: *basaas_test_steps
  build:
    docker: *node_env
    working_directory: ~/oih
    steps: *build_steps
  deploy:
    docker: *node_env
    working_directory: ~/oih
    steps: *deploy_steps
  secret-service-test:
    docker: *node_env
    working_directory: ~/oih/services/secret-service
    steps: *basaas_test_steps
workflows:
  pipeline:
    jobs:
      - deps
      - iam-test:
          requires:
            - deps
      - secret-service-test:
          requires:
            - deps
      - test:
          requires:
            - iam-test
            - secret-service-test
      - build:
          requires:
            - test
          filters: *only_master_filter
      - deploy:
          requires:
            - build
          filters: *only_master_filter
