version: "3.7"
services:
  iam:
    image: node:${NODE_VERSION}
    container_name: iam
    working_dir: /usr/src/app/services/iam
    environment:
      NODE_ENV: "development"
      LOG_LEVEL: info
      # NODE_TLS_REJECT_UNAUTHORIZED: 0
      RABBITMQ_URI: "amqp://guest:guest@rabbitmq"
      IAM_MONGODB_CONNECTION: mongodb://mongodb/${DB_IAM}
      IAM_AUTH_TYPE: "basic"
      IAM_DEBUG: "true"
      IAM_BASEURL: "http://iam.oih.dev:3099"
      IAM_ORIGINWHITELIST: "http://web-ui.iam.oih.dev:3000"
      IAM_JWT_SECRET: “secret”
      IAM_SESSION_COOKIE_SECRET: "secret"
      IAM_JWT_COOKIENAME: "oih_cookie"
      IAM_JWT_AUDIENCE: "oih-iam"
      IAM_ACC_ADMIN_USERNAME: ${DEV_IAM_ADMIN_USERNAME}
      IAM_ACC_ADMIN_PASSWORD: ${DEV_IAM_ADMIN_PASSWORD}
      IAM_ACC_SERVICEACCOUNT_PASSWORD: "secret"

      # IAM_SERVICE_CLIENT_ID: "8ce00058-5f75-435f-9026-ad952480e15a"
      # IAM_SERVICE_CLIENT_SECRET: "secret"
      PORT: "3099"
    ports:
      - ${HOST_IAM_PORT}:3099
    volumes:
      - type: bind
        source: ${HOST_REPOSITORY_ROOT}
        target: /usr/src/app
    command: yarn watch-container
    networks:
      - oih-dev

networks:
  oih-dev:
    external:
      name: oih-dev
