apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
  namespace: oih-dev-ns
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        runAsUser: 472
        fsGroup: 472
      containers:
      - name: master
        image: grafana/grafana:latest
          env:
          - name: GF_LOG_LEVEL
            value: "error"
          - name: GF_INSTALL_PLUGINS
            value: "grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource"
          volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-pdisk
        resources:
          requests:
            cpu: 0.2
            memory: 512Mi
        ports:
          - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /robots.txt
            port: 3000
          initialDelaySeconds: 120
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /robots.txt
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
  namespace: oih-dev-ns
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: redis
  type: NodePort
