env:
  node: true
plugins:
- prettier
extends:
- airbnb-base
- plugin:prettier/recommended
- plugin:import/errors
- plugin:import/warnings
rules:
  no-console: 'off'
  react/prop-types: 0
  no-restricted-syntax: 0
  no-await-in-loop: 0
  no-underscore-dangle: 0
  no-param-reassign: 0
  no-continue: 0
