apiVersion: v1
kind: Service
metadata:
  labels:
    app: ils
  name: ils
  namespace: oih-dev-ns
spec:
  type: NodePort
  selector:
      app: ils
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
