apiVersion: v1
kind: PersistentVolume
metadata:
  name: source-volume
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    server: 192.168.64.1
    path: '/Users/james/OIH/openintegrationhub'