apiVersion: v1
kind: Service
metadata:
  labels:
    app: icr
  name: icr
  namespace: oih-dev-ns
spec:
  type: NodePort
  selector:
      app: icr
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
